# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget


class Ui_MainWindow(object):
    def center_widget(self,widgets):
        screen_geometry = QDesktopWidget().screenGeometry()
        center_point = screen_geometry.center()
        widgets.move(int(center_point.x() -  widgets.width() / 2), int(center_point.y() -  widgets.height() / 2))
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(4095, 960)
        MainWindow.setMinimumSize(QtCore.QSize(450, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        # self.widget.setGeometry(QtCore.QRect(-170, 440, 120, 80))
        self.widget.setObjectName("widget")
        self.setGeometry(0, 0, self.screen().geometry().width(), self.screen().geometry().height())
        # self.showMaximized()
        self.Login_widget = QtWidgets.QWidget(self.centralwidget)
        self.Login_widget.setGeometry(QtCore.QRect(50, 10, 521, 661))
        self.center_widget(self.Login_widget)
        # screen_geometry = QDesktopWidget().screenGeometry()
        # center_point = screen_geometry.center()
        # self.Login_widget.move(int(center_point.x() -  self.Login_widget.width() / 2), int(center_point.y() -  self.Login_widget.height() / 2))
        self.Login_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.Login_widget.setObjectName("Login_widget")
        self.label = QtWidgets.QLabel(self.Login_widget)
        self.label.setGeometry(QtCore.QRect(30, 10, 461, 641))
        self.label.setStyleSheet("background-image:url(images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Login_widget)
        self.label_2.setGeometry(QtCore.QRect(190, 90, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgba(255,255,255,210);\n"
"")
        self.label_2.setObjectName("label_2")
        self.login_acc_line = QtWidgets.QLineEdit(self.Login_widget)
        self.login_acc_line.setGeometry(QtCore.QRect(120, 210, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login_acc_line.setFont(font)
        self.login_acc_line.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.login_acc_line.setObjectName("lineEdit")
        self.login_pswd_line = QtWidgets.QLineEdit(self.Login_widget)
        self.login_pswd_line.setGeometry(QtCore.QRect(120, 300, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login_pswd_line.setFont(font)
        self.login_pswd_line.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.login_pswd_line.setObjectName("login_pswd_line")
        self.Login = QtWidgets.QPushButton(self.Login_widget)
        self.Login.setGeometry(QtCore.QRect(110, 410, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Login.setFont(font)
        self.Login.setStyleSheet("QPushButton#Login {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#Login:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#Login:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.Login.setObjectName("Login")
        self.label_3 = QtWidgets.QLabel(self.Login_widget)
        self.label_3.setGeometry(QtCore.QRect(210, 480, 121, 50))
        self.label_3.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.label_3.setObjectName("label_3")
        self.Create_account = QtWidgets.QPushButton(self.Login_widget)
        self.Create_account.setGeometry(QtCore.QRect(190, 530, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Create_account.setFont(font)
        self.Create_account.setStyleSheet("QPushButton#Create_account {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#Create_account:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#Create_account:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.Create_account.setObjectName("Create_account")
        self.Create_account_widget = QtWidgets.QWidget(self.centralwidget)
        self.Create_account_widget.setGeometry(QtCore.QRect(620, 10, 521, 661))
        self.center_widget(self.Create_account_widget)
        self.Create_account_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.Create_account_widget.setObjectName("Create_account_widget")
        self.label_4 = QtWidgets.QLabel(self.Create_account_widget)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 461, 641))
        self.label_4.setStyleSheet("background-image:url(images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Create_account_widget)
        self.label_5.setGeometry(QtCore.QRect(140, 70, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255,255,255,210);\n"
"")
        self.label_5.setObjectName("label_5")
        self.create_name_line = QtWidgets.QLineEdit(self.Create_account_widget)
        self.create_name_line.setGeometry(QtCore.QRect(130, 170, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_name_line.setFont(font)
        self.create_name_line.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.create_name_line.setObjectName("create_name_line")
        self.create_pswd_line1 = QtWidgets.QLineEdit(self.Create_account_widget)
        self.create_pswd_line1.setGeometry(QtCore.QRect(130, 330, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_pswd_line1.setFont(font)
        self.create_pswd_line1.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.create_pswd_line1.setObjectName("create_phone_line")
        self.Create_account_button = QtWidgets.QPushButton(self.Create_account_widget)
        self.Create_account_button.setGeometry(QtCore.QRect(200, 510, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Create_account_button.setFont(font)
        self.Create_account_button.setStyleSheet("QPushButton#Create_account_button {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#Create_account_button:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#Create_account_button:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.Create_account_button.setObjectName("Create_account_button")
        self.create_deposite_amount1 = QtWidgets.QLineEdit(self.Create_account_widget)
        self.create_deposite_amount1.setGeometry(QtCore.QRect(130, 410, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_deposite_amount1.setFont(font)
        self.create_deposite_amount1.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.create_deposite_amount1.setObjectName("create_deposite_amount1")
        self.create_phone_line1 = QtWidgets.QLineEdit(self.Create_account_widget)
        self.create_phone_line1.setGeometry(QtCore.QRect(130, 250, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_phone_line1.setFont(font)
        self.create_phone_line1.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.create_phone_line1.setObjectName("create_phone_line1")
        self.create_acc_x_button = QtWidgets.QPushButton(self.Create_account_widget)
        self.create_acc_x_button.setGeometry(QtCore.QRect(460, 20, 21, 21))
        self.create_acc_x_button.setStyleSheet("QPushButton#create_acc_x_button {\n"
"border-image:url(images/x-mark-5-256.png) 0 0 0 0 streatch streatch;"
"}\n"
"QPushButton#create_acc_x_button:hover {\n"
"border-image:url(images/x-mark-3-256.png) 0 0 0 0 streatch streatch;\n"
"}\n")
        self.create_acc_x_button.setText("")
        self.create_acc_x_button.setObjectName("create_acc_x_button")
        
        self.account_details_widget = QtWidgets.QWidget(self.centralwidget)
        self.account_details_widget.setGeometry(QtCore.QRect(2380, 510, 521, 301))
        self.center_widget(self.account_details_widget)
        self.account_details_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.account_details_widget.setObjectName("account_details_widget")
        self.account_details_background = QtWidgets.QLabel(self.account_details_widget)
        self.account_details_background.setGeometry(QtCore.QRect(30, 10, 461, 281))
        self.account_details_background.setStyleSheet("background-image:url(images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.account_details_background.setText("")
        self.account_details_background.setObjectName("account_details_background")
        self.account_details_thanks_ok = QtWidgets.QPushButton(self.account_details_widget)
        self.account_details_thanks_ok.setGeometry(QtCore.QRect(180, 220, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.account_details_thanks_ok.setFont(font)
        self.account_details_thanks_ok.setStyleSheet("QPushButton#account_details_thanks_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#account_details_thanks_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#account_details_thanks_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.account_details_thanks_ok.setObjectName("account_details_thanks_ok")
        self.account_details_head = QtWidgets.QLabel(self.account_details_widget)
        self.account_details_head.setGeometry(QtCore.QRect(150, 20, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.account_details_head.setFont(font)
        self.account_details_head.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.account_details_head.setObjectName("account_details_head")
        self.account_details_user_icon = QtWidgets.QLabel(self.account_details_widget)
        self.account_details_user_icon.setGeometry(QtCore.QRect(100, 30, 31, 31))
        self.account_details_user_icon.setStyleSheet("border-image:url(images/icons8-user-24.png) 0 0 0 0 stretch stretch;")
        self.account_details_user_icon.setText("")
        self.account_details_user_icon.setObjectName("account_details_user_icon")
        self.account_number = QtWidgets.QLabel(self.account_details_widget)
        self.account_number.setGeometry(QtCore.QRect(100, 160, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.account_number.setFont(font)
        self.account_number.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.account_number.setObjectName("account_number")
        self.account_number_lable = QtWidgets.QLabel(self.account_details_widget)
        self.account_number_lable.setGeometry(QtCore.QRect(260, 160, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.account_number_lable.setFont(font)
        self.account_number_lable.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.account_number_lable.setObjectName("account_number_lable")
        self.account_user_name = QtWidgets.QLabel(self.account_details_widget)
        self.account_user_name.setGeometry(QtCore.QRect(100, 120, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.account_user_name.setFont(font)
        self.account_user_name.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.account_user_name.setObjectName("account_user_name")
        self.account_user_name_lable = QtWidgets.QLabel(self.account_details_widget)
        self.account_user_name_lable.setGeometry(QtCore.QRect(170, 120, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.account_user_name_lable.setFont(font)
        self.account_user_name_lable.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.account_user_name_lable.setObjectName("account_user_name_lable")
        self.account_details_created_icon = QtWidgets.QLabel(self.account_details_widget)
        self.account_details_created_icon.setGeometry(QtCore.QRect(390, 180, 71, 71))
        self.account_details_created_icon.setStyleSheet("border-image:url(images/checklist.png) 0 0 0 0 stretch stretch;")
        self.account_details_created_icon.setText("")
        self.account_details_created_icon.setObjectName("account_details_created_icon")
        self.account_number_2 = QtWidgets.QLabel(self.account_details_widget)
        self.account_number_2.setGeometry(QtCore.QRect(100, 70, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.account_number_2.setFont(font)
        self.account_number_2.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.account_number_2.setObjectName("account_number_2")
        
        self.Banking = QtWidgets.QWidget(self.centralwidget)
        self.Banking.setGeometry(QtCore.QRect(1170, 10, 1061, 661))
        self.center_widget(self.Banking)
        self.Banking.setObjectName("Banking")
        self.label_6 = QtWidgets.QLabel(self.Banking)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 1021, 641))
        self.label_6.setStyleSheet("border-image:url(images/rupee.jpg);\n"
"border-radius:10px;\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.bank_deposit_button = QtWidgets.QPushButton(self.Banking)
        self.bank_deposit_button.setGeometry(QtCore.QRect(640, 180, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.bank_deposit_button.setFont(font)
        self.bank_deposit_button.setStyleSheet("QPushButton#bank_deposit_button {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#bank_deposit_button:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#bank_deposit_button:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.bank_deposit_button.setObjectName("bank_deposit_button")
        self.bank_withdrawl_button = QtWidgets.QPushButton(self.Banking)
        self.bank_withdrawl_button.setGeometry(QtCore.QRect(640, 270, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.bank_withdrawl_button.setFont(font)
        self.bank_withdrawl_button.setStyleSheet("QPushButton#bank_withdrawl_button {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#bank_withdrawl_button:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#bank_withdrawl_button:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.bank_withdrawl_button.setObjectName("bank_withdrawl_button")
        self.bank_transfer_button = QtWidgets.QPushButton(self.Banking)
        self.bank_transfer_button.setGeometry(QtCore.QRect(640, 360, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.bank_transfer_button.setFont(font)
        self.bank_transfer_button.setStyleSheet("QPushButton#bank_transfer_button {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#bank_transfer_button:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#bank_transfer_button:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.bank_transfer_button.setObjectName("bank_transfer_button")
        self.bank_check_balance = QtWidgets.QPushButton(self.Banking)
        self.bank_check_balance.setGeometry(QtCore.QRect(640, 450, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.bank_check_balance.setFont(font)
        self.bank_check_balance.setStyleSheet("QPushButton#bank_check_balance {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#bank_check_balance:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#bank_check_balance:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.bank_check_balance.setObjectName("bank_check_balance")
        self.log_out_button = QtWidgets.QPushButton(self.Banking)
        self.log_out_button.setGeometry(QtCore.QRect(910, 580, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.log_out_button.setFont(font)
        self.log_out_button.setStyleSheet("QPushButton#log_out_button {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#log_out_button:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#log_out_button:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.log_out_button.setObjectName("log_out_button")
        self.user_icon = QtWidgets.QLabel(self.Banking)
        self.user_icon.setGeometry(QtCore.QRect(50, 40, 31, 31))
        self.user_icon.setStyleSheet("border-image:url(images/icons8-user-24.png) 0 0 0 0 stretch stretch;")
        self.user_icon.setText("")
        self.user_icon.setObjectName("user_icon")
        self.user_name = QtWidgets.QLabel(self.Banking)
        self.user_name.setGeometry(QtCore.QRect(90, 50, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_name.setFont(font)
        self.user_name.setStyleSheet("color:rgba(255,255,255,200);")
        self.user_name.setObjectName("user_name")
        self.label_7 = QtWidgets.QLabel(self.Banking)
        self.label_7.setGeometry(QtCore.QRect(680, 50, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.label_7.setObjectName("label_7")
        self.display_acc_number = QtWidgets.QLabel(self.Banking)
        self.display_acc_number.setGeometry(QtCore.QRect(820, 50, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.display_acc_number.setFont(font)
        self.display_acc_number.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.display_acc_number.setObjectName("label_8")
        self.deposit_widget = QtWidgets.QWidget(self.centralwidget)
        self.deposit_widget.setGeometry(QtCore.QRect(2390, 10, 521, 451))
        self.center_widget(self.deposit_widget)
        self.deposit_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.deposit_widget.setObjectName("deposit_widget")
        self.label_9 = QtWidgets.QLabel(self.deposit_widget)
        self.label_9.setGeometry(QtCore.QRect(30, 10, 461, 411))
        self.label_9.setStyleSheet("background-image:url(images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.deposit_head = QtWidgets.QLabel(self.deposit_widget)
        self.deposit_head.setGeometry(QtCore.QRect(200, 70, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.deposit_head.setFont(font)
        self.deposit_head.setStyleSheet("color:rgba(255,255,255,210);\n"
"")
        self.deposit_head.setObjectName("deposit_head")
        self.deposit_amount = QtWidgets.QLineEdit(self.deposit_widget)
        self.deposit_amount.setGeometry(QtCore.QRect(130, 190, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deposit_amount.setFont(font)
        self.deposit_amount.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.deposit_amount.setObjectName("deposit_amount")
        self.deposit_ok = QtWidgets.QPushButton(self.deposit_widget)
        self.deposit_ok.setGeometry(QtCore.QRect(190, 310, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deposit_ok.setFont(font)
        self.deposit_ok.setStyleSheet("QPushButton#deposit_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#deposit_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#deposit_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.deposit_ok.setObjectName("deposit_ok")
        self.deposite_x_button = QtWidgets.QPushButton(self.deposit_widget)
        self.deposite_x_button.setGeometry(QtCore.QRect(460, 20, 21, 21))
        self.deposite_x_button.setStyleSheet("QPushButton#deposite_x_button {\n"
"border-image:url(images/x-mark-5-256.png) 0 0 0 0 streatch streatch;"
"}\n"
"QPushButton#deposite_x_button:hover {\n"
"border-image:url(images/x-mark-3-256.png) 0 0 0 0 streatch streatch;\n"
"}\n")
        self.deposite_x_button.setText("")
        self.deposite_x_button.setObjectName("deposite_x_button")
        
        self.withdrawl_widget = QtWidgets.QWidget(self.centralwidget)
        self.withdrawl_widget.setGeometry(QtCore.QRect(2980, 10, 521, 451))
        self.center_widget(self.withdrawl_widget)
        self.withdrawl_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.withdrawl_widget.setObjectName("withdrawl_widget")
        self.label_15 = QtWidgets.QLabel(self.withdrawl_widget)
        self.label_15.setGeometry(QtCore.QRect(30, 10, 461, 411))
        self.label_15.setStyleSheet("background-image:url(images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.withdrawl_head = QtWidgets.QLabel(self.withdrawl_widget)
        self.withdrawl_head.setGeometry(QtCore.QRect(190, 70, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.withdrawl_head.setFont(font)
        self.withdrawl_head.setStyleSheet("color:rgba(255,255,255,210);\n"
"")
        self.withdrawl_head.setObjectName("withdrawl_head")
        self.withdrawl_amount = QtWidgets.QLineEdit(self.withdrawl_widget)
        self.withdrawl_amount.setGeometry(QtCore.QRect(130, 190, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.withdrawl_amount.setFont(font)
        self.withdrawl_amount.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.withdrawl_amount.setObjectName("withdrawl_amount")
        self.withdrawl_ok = QtWidgets.QPushButton(self.withdrawl_widget)
        self.withdrawl_ok.setGeometry(QtCore.QRect(190, 310, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.withdrawl_ok.setFont(font)
        self.withdrawl_ok.setStyleSheet("QPushButton#withdrawl_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#withdrawl_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#withdrawl_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.withdrawl_ok.setObjectName("withdrawl_ok")
        self.withdrawl_x_button = QtWidgets.QPushButton(self.withdrawl_widget)
        self.withdrawl_x_button.setGeometry(QtCore.QRect(460, 20, 21, 21))
        self.withdrawl_x_button.setStyleSheet("QPushButton#withdrawl_x_button {\n"
"border-image:url(images/x-mark-5-256.png) 0 0 0 0 streatch streatch;"
"}\n"

"QPushButton#withdrawl_x_button:hover {\n"
"border-image:url(images/x-mark-3-256.png) 0 0 0 0 streatch streatch;\n"
"}\n")
        self.withdrawl_x_button.setText("")
        self.withdrawl_x_button.setObjectName("withdrawl_x_button")
        
        self.transfer_widget = QtWidgets.QWidget(self.centralwidget)
        self.transfer_widget.setGeometry(QtCore.QRect(3550, 10, 521, 451))
        self.center_widget(self.transfer_widget)
        self.transfer_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.transfer_widget.setObjectName("transfer_widget")
        self.label16 = QtWidgets.QLabel(self.transfer_widget)
        self.label16.setGeometry(QtCore.QRect(30, 10, 461, 411))
        self.label16.setStyleSheet("background-image:url(images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label16.setText("")
        self.label16.setObjectName("label16")
        self.transfer_head = QtWidgets.QLabel(self.transfer_widget)
        self.transfer_head.setGeometry(QtCore.QRect(190, 70, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.transfer_head.setFont(font)
        self.transfer_head.setStyleSheet("color:rgba(255,255,255,210);\n"
"")
        self.transfer_head.setObjectName("transfer_head")
        self.transfer_account = QtWidgets.QLineEdit(self.transfer_widget)
        self.transfer_account.setGeometry(QtCore.QRect(130, 160, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.transfer_account.setFont(font)
        self.transfer_account.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.transfer_account.setObjectName("transfer_account")
        self.transfer_ok = QtWidgets.QPushButton(self.transfer_widget)
        self.transfer_ok.setGeometry(QtCore.QRect(200, 340, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.transfer_ok.setFont(font)
        self.transfer_ok.setStyleSheet("QPushButton#transfer_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#transfer_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#transfer_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.transfer_ok.setObjectName("transfer_ok")
        self.transfer_amount = QtWidgets.QLineEdit(self.transfer_widget)
        self.transfer_amount.setGeometry(QtCore.QRect(130, 240, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.transfer_amount.setFont(font)
        self.transfer_amount.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.transfer_amount.setObjectName("transfer_amount")
        self.transfer_x_button = QtWidgets.QPushButton(self.transfer_widget)
        self.transfer_x_button.setGeometry(QtCore.QRect(460, 20, 21, 21))
        self.transfer_x_button.setStyleSheet("QPushButton#transfer_x_button {\n"
"border-image:url(images/x-mark-5-256.png) 0 0 0 0 streatch streatch;"
"}\n"
"QPushButton#transfer_x_button:hover {\n"
"border-image:url(images/x-mark-3-256.png) 0 0 0 0 streatch streatch;\n"
"}\n")
        self.transfer_x_button.setText("")
        self.transfer_x_button.setObjectName("transfer_x_button")
        
        self.check_balance_widget = QtWidgets.QWidget(self.centralwidget)
        self.check_balance_widget.setGeometry(QtCore.QRect(2980, 480, 521, 371))
        self.center_widget(self.check_balance_widget)
        self.check_balance_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.check_balance_widget.setObjectName("check_balance_widget")
        self.label16_3 = QtWidgets.QLabel(self.check_balance_widget)
        self.label16_3.setGeometry(QtCore.QRect(30, 10, 461, 341))
        self.label16_3.setStyleSheet("background-image:url(images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label16_3.setText("")
        self.label16_3.setObjectName("label16_3")
        self.balance_ok = QtWidgets.QPushButton(self.check_balance_widget)
        self.balance_ok.setGeometry(QtCore.QRect(190, 280, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.balance_ok.setFont(font)
        self.balance_ok.setStyleSheet("QPushButton#balance_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#balance_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#balance_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.balance_ok.setObjectName("balance_ok")
        self.available_balance_head = QtWidgets.QLabel(self.check_balance_widget)
        self.available_balance_head.setGeometry(QtCore.QRect(120, 100, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.available_balance_head.setFont(font)
        self.available_balance_head.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.available_balance_head.setObjectName("available_balance_head")
        self.balance_amount = QtWidgets.QLabel(self.check_balance_widget)
        self.balance_amount.setGeometry(QtCore.QRect(230, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        self.balance_amount.setFont(font)
        self.balance_amount.setStyleSheet("color:rgba(255,255,255,230);\n"
"")
        self.balance_amount.setObjectName("balance_amount")
        self.rupee_icon = QtWidgets.QLabel(self.check_balance_widget)
        self.rupee_icon.setGeometry(QtCore.QRect(200, 178, 31, 31))
        self.rupee_icon.setStyleSheet("border-image:  url(images/icons8-rupee-96.png) 0 0 0 0 stretch stretch;\n"
"opacity:0.3;")
        self.rupee_icon.setText("")
        self.rupee_icon.setObjectName("rupee_icon")
        self.transaction_completed_widget = QtWidgets.QWidget(self.centralwidget)
        self.transaction_completed_widget.setGeometry(QtCore.QRect(3560, 500, 521, 261))
        self.transaction_completed_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.transaction_completed_widget.setObjectName("transaction_completed_widget")
        self.label16_4 = QtWidgets.QLabel(self.transaction_completed_widget)
        self.label16_4.setGeometry(QtCore.QRect(30, 10, 461, 241))
        self.center_widget(self.transaction_completed_widget)
        self.label16_4.setStyleSheet("background-image:url(images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label16_4.setText("")
        self.label16_4.setObjectName("label16_4")
        self.transaction_completed_ok = QtWidgets.QPushButton(self.transaction_completed_widget)
        self.transaction_completed_ok.setGeometry(QtCore.QRect(190, 190, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.transaction_completed_ok.setFont(font)
        self.transaction_completed_ok.setStyleSheet("QPushButton#transaction_completed_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#transaction_completed_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#transaction_completed_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.transaction_completed_ok.setObjectName("transaction_completed_ok")
        self.transation_completed_head = QtWidgets.QLabel(self.transaction_completed_widget)
        self.transation_completed_head.setGeometry(QtCore.QRect(70, 50, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.transation_completed_head.setFont(font)
        self.transation_completed_head.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.transation_completed_head.setObjectName("transation_completed_head")
        self.completed_icon = QtWidgets.QLabel(self.transaction_completed_widget)
        self.completed_icon.setGeometry(QtCore.QRect(230, 110, 61, 61))
        self.completed_icon.setStyleSheet("border-image:url(images/checklist.png) 0 0 0 0 stretch stretch;")
        self.completed_icon.setText("")
        self.completed_icon.setObjectName("completed_icon")
        
        self.transaction_aborted_widget = QtWidgets.QWidget(self.centralwidget)
        self.transaction_aborted_widget.setGeometry(QtCore.QRect(2400, 510, 521, 261))
        self.transaction_aborted_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.transaction_aborted_widget.setObjectName("transaction_aborted_widget")
        self.transaction_aborted_background = QtWidgets.QLabel(self.transaction_aborted_widget)
        self.transaction_aborted_background.setGeometry(QtCore.QRect(30, 10, 461, 241))
        self.center_widget(self.transaction_aborted_widget)
        self.transaction_aborted_background.setStyleSheet("background-image:url(images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.transaction_aborted_background.setText("")
        self.transaction_aborted_background.setObjectName("transaction_aborted_background")
        self.transaction_aborted_ok = QtWidgets.QPushButton(self.transaction_aborted_widget)
        self.transaction_aborted_ok.setGeometry(QtCore.QRect(190, 190, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.transaction_aborted_ok.setFont(font)
        self.transaction_aborted_ok.setStyleSheet("QPushButton#transaction_aborted_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#transaction_aborted_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#transaction_aborted_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.transaction_aborted_ok.setObjectName("transaction_aborted_ok")
        self.transation_aborted_head = QtWidgets.QLabel(self.transaction_aborted_widget)
        self.transation_aborted_head.setGeometry(QtCore.QRect(90, 50, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.transation_aborted_head.setFont(font)
        self.transation_aborted_head.setStyleSheet("color:rgba(255,100,25,200);\n"
"")
        self.transation_aborted_head.setObjectName("transation_aborted_head")
        self.transaction_aborted_Xicon = QtWidgets.QLabel(self.transaction_aborted_widget)
        self.transaction_aborted_Xicon.setGeometry(QtCore.QRect(230, 100, 71, 71))
        self.transaction_aborted_Xicon.setStyleSheet("border-image:url(images/cancel.png) 0 0 0 0 stretch stretch;")
        self.transaction_aborted_Xicon.setText("")
        self.transaction_aborted_Xicon.setObjectName("transaction_aborted_Xicon")
        
        self.authentication_failed_widget = QtWidgets.QWidget(self.centralwidget)
        self.authentication_failed_widget.setGeometry(QtCore.QRect(1850, 650, 521, 261))
        self.center_widget(self.authentication_failed_widget)
        self.authentication_failed_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.authentication_failed_widget.setObjectName("authentication_failed_widget")
        self.authentication_failed_background = QtWidgets.QLabel(self.authentication_failed_widget)
        self.authentication_failed_background.setGeometry(QtCore.QRect(30, 10, 461, 241))
        self.authentication_failed_background.setStyleSheet("background-image:url(images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.authentication_failed_background.setText("")
        self.authentication_failed_background.setObjectName("authentication_failed_background")
        self.authentication_failed_ok = QtWidgets.QPushButton(self.authentication_failed_widget)
        self.authentication_failed_ok.setGeometry(QtCore.QRect(190, 190, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.authentication_failed_ok.setFont(font)
        self.authentication_failed_ok.setStyleSheet("QPushButton#authentication_failed_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#authentication_failed_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#authentication_failed_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.authentication_failed_ok.setObjectName("authentication_failed_ok")
        self.authentication_failed_head = QtWidgets.QLabel(self.authentication_failed_widget)
        self.authentication_failed_head.setGeometry(QtCore.QRect(90, 50, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.authentication_failed_head.setFont(font)
        self.authentication_failed_head.setStyleSheet("color:rgba(255,100,25,200);\n"
"")
        self.authentication_failed_head.setObjectName("authentication_failed_head")
        self.authentication_failed_warning_icon = QtWidgets.QLabel(self.authentication_failed_widget)
        self.authentication_failed_warning_icon.setGeometry(QtCore.QRect(230, 100, 71, 71))
        self.authentication_failed_warning_icon.setStyleSheet("border-image:url(images/icons8-warning-96.png) 0 0 0 0 stretch stretch;")
        self.authentication_failed_warning_icon.setText("")
        self.authentication_failed_warning_icon.setObjectName("authentication_failed_warning_icon")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 4095, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Log In"))
        self.login_acc_line.setPlaceholderText(_translate("MainWindow", "Account Number"))
        self.login_pswd_line.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Login.setText(_translate("MainWindow", "Log In"))
        self.label_3.setText(_translate("MainWindow", "Don\'t have acount?"))
        self.Create_account.setText(_translate("MainWindow", "Create Account"))
        self.label_5.setText(_translate("MainWindow", "Create Account"))
        self.create_name_line.setPlaceholderText(_translate("MainWindow", "Name"))
        self.create_pswd_line1.setPlaceholderText(_translate("MainWindow", "Create Password"))
        self.Create_account_button.setText(_translate("MainWindow", "Create Account"))
        self.create_deposite_amount1.setPlaceholderText(_translate("MainWindow", "Deposit Amount"))
        self.create_phone_line1.setPlaceholderText(_translate("MainWindow", "Phone Number"))
        self.account_details_thanks_ok.setText(_translate("MainWindow", "Thanks"))
        self.account_details_head.setText(_translate("MainWindow", "Account Details"))
        self.account_number.setText(_translate("MainWindow", "Account Number:"))
        self.account_number_lable.setText(_translate("MainWindow", "XXX XXX XXX"))
        self.account_user_name.setText(_translate("MainWindow", "Name :"))
        self.account_user_name_lable.setText(_translate("MainWindow", "XXX XXX XXX"))
        self.account_number_2.setText(_translate("MainWindow", "Congrats! Your account has created succesfully"))
        self.bank_deposit_button.setText(_translate("MainWindow", "Deposit"))
        self.bank_withdrawl_button.setText(_translate("MainWindow", "Withdrawl"))
        self.bank_transfer_button.setText(_translate("MainWindow", "Transfer"))
        self.bank_check_balance.setText(_translate("MainWindow", "Check Balance"))
        self.log_out_button.setText(_translate("MainWindow", "Log Out"))
        self.user_name.setText(_translate("MainWindow", "User Name"))
        self.label_7.setText(_translate("MainWindow", "Account Number:"))
        self.display_acc_number.setText(_translate("MainWindow", "XXX XXX XXX"))
        self.deposit_head.setText(_translate("MainWindow", "Deposit"))
        self.deposit_amount.setPlaceholderText(_translate("MainWindow", "Enter Amount"))
        self.deposit_ok.setText(_translate("MainWindow", "Ok"))
        self.withdrawl_head.setText(_translate("MainWindow", "Withdraw"))
        self.withdrawl_amount.setPlaceholderText(_translate("MainWindow", "Enter Amount"))
        self.withdrawl_ok.setText(_translate("MainWindow", "Ok"))
        self.transfer_head.setText(_translate("MainWindow", "Transfer"))
        self.transfer_account.setPlaceholderText(_translate("MainWindow", "Receiver Account NUmber"))
        self.transfer_ok.setText(_translate("MainWindow", "Ok"))
        self.transfer_amount.setPlaceholderText(_translate("MainWindow", "Enter Amount"))
        self.balance_ok.setText(_translate("MainWindow", "Ok"))
        self.available_balance_head.setText(_translate("MainWindow", "Available Balance"))
        self.balance_amount.setText(_translate("MainWindow", "XXXX"))
        self.transaction_completed_ok.setText(_translate("MainWindow", "Ok"))
        self.transation_completed_head.setText(_translate("MainWindow", "Transaction Succesful"))
        self.transaction_aborted_ok.setText(_translate("MainWindow", "Ok"))
        self.transation_aborted_head.setText(_translate("MainWindow", "Invalid Transaction!"))
        self.authentication_failed_ok.setText(_translate("MainWindow", "Ok"))
        self.authentication_failed_head.setText(_translate("MainWindow", "Login Failed!"))
# import resources_rc
# if __name__=="__main__":
#         import sys
#         app = QtWidgets.QApplication(sys.argv)
#         MainWindow = QtWidgets.QMainWindow()
#         ui = Ui_MainWindow()
#         ui.setupUi(MainWindow)
#         MainWindow.show()
#         sys.exit(app.exec_())
        
