# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(4095, 960)
        MainWindow.setMinimumSize(QtCore.QSize(450, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-170, 440, 120, 80))
        self.widget.setObjectName("widget")
        self.Login_widget = QtWidgets.QWidget(self.centralwidget)
        self.Login_widget.setGeometry(QtCore.QRect(50, 10, 521, 661))
        self.Login_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.Login_widget.setObjectName("Login_widget")
        self.label = QtWidgets.QLabel(self.Login_widget)
        self.label.setGeometry(QtCore.QRect(30, 10, 461, 641))
        self.label.setStyleSheet("background-image:url(:/images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Login_widget)
        self.label_2.setGeometry(QtCore.QRect(190, 90, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgba(255,255,255,210);\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.Login_widget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 210, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Login_widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 300, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Login = QtWidgets.QPushButton(self.Login_widget)
        self.Login.setGeometry(QtCore.QRect(110, 410, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Login.setFont(font)
        self.Login.setStyleSheet("QPushButton#Login {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"transition: 0.9s;\n"
"}\n"
"\n"
"QPushButton#Login:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#Login:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.Login.setObjectName("Login")
        self.label_3 = QtWidgets.QLabel(self.Login_widget)
        self.label_3.setGeometry(QtCore.QRect(210, 480, 121, 50))
        self.label_3.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.label_3.setObjectName("label_3")
        self.Create_account = QtWidgets.QPushButton(self.Login_widget)
        self.Create_account.setGeometry(QtCore.QRect(190, 530, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Create_account.setFont(font)
        self.Create_account.setStyleSheet("QPushButton#Create_account {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#Create_account:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#Create_account:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.Create_account.setObjectName("Create_account")
        self.Create_account_widget = QtWidgets.QWidget(self.centralwidget)
        self.Create_account_widget.setGeometry(QtCore.QRect(620, 10, 521, 661))
        self.Create_account_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.Create_account_widget.setObjectName("Create_account_widget")
        self.label_4 = QtWidgets.QLabel(self.Create_account_widget)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 461, 641))
        self.label_4.setStyleSheet("background-image:url(:/images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Create_account_widget)
        self.label_5.setGeometry(QtCore.QRect(140, 70, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255,255,255,210);\n"
"")
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Create_account_widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 170, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.Create_account_widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 330, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.Create_account_2 = QtWidgets.QPushButton(self.Create_account_widget)
        self.Create_account_2.setGeometry(QtCore.QRect(200, 510, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Create_account_2.setFont(font)
        self.Create_account_2.setStyleSheet("QPushButton#Create_account_2 {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#Create_account_2:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#Create_account_2:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.Create_account_2.setObjectName("Create_account_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.Create_account_widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 410, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.Create_account_widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 250, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.Banking = QtWidgets.QWidget(self.centralwidget)
        self.Banking.setGeometry(QtCore.QRect(1170, -20, 1061, 661))
        self.Banking.setObjectName("Banking")
        self.label_6 = QtWidgets.QLabel(self.Banking)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 1021, 641))
        self.label_6.setStyleSheet("border-image:url(:/images/rupee.jpg);\n"
"border-radius:10px;\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.deposit = QtWidgets.QPushButton(self.Banking)
        self.deposit.setGeometry(QtCore.QRect(640, 180, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.deposit.setFont(font)
        self.deposit.setStyleSheet("QPushButton#deposit {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"transition: 0.9s;\n"
"}\n"
"\n"
"QPushButton#deposit:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#deposit:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.deposit.setObjectName("deposit")
        self.withdrawl = QtWidgets.QPushButton(self.Banking)
        self.withdrawl.setGeometry(QtCore.QRect(640, 270, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.withdrawl.setFont(font)
        self.withdrawl.setStyleSheet("QPushButton#withdrawl {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"transition: 0.9s;\n"
"}\n"
"\n"
"QPushButton#withdrawl:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#withdrawl:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.withdrawl.setObjectName("withdrawl")
        self.transfer = QtWidgets.QPushButton(self.Banking)
        self.transfer.setGeometry(QtCore.QRect(640, 360, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.transfer.setFont(font)
        self.transfer.setStyleSheet("QPushButton#transfer {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"transition: 0.9s;\n"
"}\n"
"\n"
"QPushButton#transfer:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#transfer:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.transfer.setObjectName("transfer")
        self.check_balance = QtWidgets.QPushButton(self.Banking)
        self.check_balance.setGeometry(QtCore.QRect(640, 450, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.check_balance.setFont(font)
        self.check_balance.setStyleSheet("QPushButton#check_balance {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"transition: 0.9s;\n"
"}\n"
"\n"
"QPushButton#check_balance:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#check_balance:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.check_balance.setObjectName("check_balance")
        self.log_out = QtWidgets.QPushButton(self.Banking)
        self.log_out.setGeometry(QtCore.QRect(910, 580, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.log_out.setFont(font)
        self.log_out.setStyleSheet("QPushButton#log_out {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"transition: 0.9s;\n"
"}\n"
"\n"
"QPushButton#log_out:hover {\n"
"background-color:qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#log_out:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.log_out.setObjectName("log_out")
        self.user_icon = QtWidgets.QLabel(self.Banking)
        self.user_icon.setGeometry(QtCore.QRect(50, 40, 31, 31))
        self.user_icon.setStyleSheet("border-image:url(:/images/icons8-user-24.png) 0 0 0 0 stretch stretch;")
        self.user_icon.setText("")
        self.user_icon.setObjectName("user_icon")
        self.user_name = QtWidgets.QLabel(self.Banking)
        self.user_name.setGeometry(QtCore.QRect(90, 50, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_name.setFont(font)
        self.user_name.setStyleSheet("color:rgba(255,255,255,200);")
        self.user_name.setObjectName("user_name")
        self.label_7 = QtWidgets.QLabel(self.Banking)
        self.label_7.setGeometry(QtCore.QRect(680, 50, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Banking)
        self.label_8.setGeometry(QtCore.QRect(820, 50, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.label_8.setObjectName("label_8")
        self.diposit_widget = QtWidgets.QWidget(self.centralwidget)
        self.diposit_widget.setGeometry(QtCore.QRect(2390, 10, 521, 451))
        self.diposit_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.diposit_widget.setObjectName("diposit_widget")
        self.label_9 = QtWidgets.QLabel(self.diposit_widget)
        self.label_9.setGeometry(QtCore.QRect(30, 10, 461, 411))
        self.label_9.setStyleSheet("background-image:url(:/images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.deposit_head = QtWidgets.QLabel(self.diposit_widget)
        self.deposit_head.setGeometry(QtCore.QRect(200, 70, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.deposit_head.setFont(font)
        self.deposit_head.setStyleSheet("color:rgba(255,255,255,210);\n"
"")
        self.deposit_head.setObjectName("deposit_head")
        self.deposit_amount = QtWidgets.QLineEdit(self.diposit_widget)
        self.deposit_amount.setGeometry(QtCore.QRect(130, 190, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deposit_amount.setFont(font)
        self.deposit_amount.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.deposit_amount.setObjectName("deposit_amount")
        self.deposit_ok = QtWidgets.QPushButton(self.diposit_widget)
        self.deposit_ok.setGeometry(QtCore.QRect(190, 310, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deposit_ok.setFont(font)
        self.deposit_ok.setStyleSheet("QPushButton#deposit_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#deposit_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#deposit_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.deposit_ok.setObjectName("deposit_ok")
        self.pushButton = QtWidgets.QPushButton(self.diposit_widget)
        self.pushButton.setGeometry(QtCore.QRect(460, 20, 21, 21))
        self.pushButton.setStyleSheet("border-image:url(:/images/x-mark-3-256.png) 0 0 0 0 streatch streatch;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.withdrawl_widget = QtWidgets.QWidget(self.centralwidget)
        self.withdrawl_widget.setGeometry(QtCore.QRect(2980, 10, 521, 451))
        self.withdrawl_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.withdrawl_widget.setObjectName("withdrawl_widget")
        self.label_15 = QtWidgets.QLabel(self.withdrawl_widget)
        self.label_15.setGeometry(QtCore.QRect(30, 10, 461, 411))
        self.label_15.setStyleSheet("background-image:url(:/images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.withdrawl_head = QtWidgets.QLabel(self.withdrawl_widget)
        self.withdrawl_head.setGeometry(QtCore.QRect(190, 70, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.withdrawl_head.setFont(font)
        self.withdrawl_head.setStyleSheet("color:rgba(255,255,255,210);\n"
"")
        self.withdrawl_head.setObjectName("withdrawl_head")
        self.withdrawl_amount = QtWidgets.QLineEdit(self.withdrawl_widget)
        self.withdrawl_amount.setGeometry(QtCore.QRect(130, 190, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.withdrawl_amount.setFont(font)
        self.withdrawl_amount.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.withdrawl_amount.setObjectName("withdrawl_amount")
        self.withdrawl_ok = QtWidgets.QPushButton(self.withdrawl_widget)
        self.withdrawl_ok.setGeometry(QtCore.QRect(190, 310, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.withdrawl_ok.setFont(font)
        self.withdrawl_ok.setStyleSheet("QPushButton#withdrawl_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#withdrawl_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#withdrawl_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.withdrawl_ok.setObjectName("withdrawl_ok")
        self.transfer_widget = QtWidgets.QWidget(self.centralwidget)
        self.transfer_widget.setGeometry(QtCore.QRect(3550, 10, 521, 451))
        self.transfer_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.transfer_widget.setObjectName("transfer_widget")
        self.label16 = QtWidgets.QLabel(self.transfer_widget)
        self.label16.setGeometry(QtCore.QRect(30, 10, 461, 411))
        self.label16.setStyleSheet("background-image:url(:/images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label16.setText("")
        self.label16.setObjectName("label16")
        self.transfer_head = QtWidgets.QLabel(self.transfer_widget)
        self.transfer_head.setGeometry(QtCore.QRect(190, 70, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.transfer_head.setFont(font)
        self.transfer_head.setStyleSheet("color:rgba(255,255,255,210);\n"
"")
        self.transfer_head.setObjectName("transfer_head")
        self.transfer_account = QtWidgets.QLineEdit(self.transfer_widget)
        self.transfer_account.setGeometry(QtCore.QRect(130, 160, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.transfer_account.setFont(font)
        self.transfer_account.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.transfer_account.setObjectName("transfer_account")
        self.transfer_ok = QtWidgets.QPushButton(self.transfer_widget)
        self.transfer_ok.setGeometry(QtCore.QRect(200, 340, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.transfer_ok.setFont(font)
        self.transfer_ok.setStyleSheet("QPushButton#transfer_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#transfer_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#transfer_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.transfer_ok.setObjectName("transfer_ok")
        self.transfer_amount = QtWidgets.QLineEdit(self.transfer_widget)
        self.transfer_amount.setGeometry(QtCore.QRect(130, 240, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.transfer_amount.setFont(font)
        self.transfer_amount.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(240, 240, 250);\n"
"color:rgba(255,255,255,190);\n"
"padding:7px;\n"
"")
        self.transfer_amount.setObjectName("transfer_amount")
        self.balance_widget = QtWidgets.QWidget(self.centralwidget)
        self.balance_widget.setGeometry(QtCore.QRect(2980, 480, 521, 371))
        self.balance_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.balance_widget.setObjectName("balance_widget")
        self.label16_3 = QtWidgets.QLabel(self.balance_widget)
        self.label16_3.setGeometry(QtCore.QRect(30, 10, 461, 341))
        self.label16_3.setStyleSheet("background-image:url(:/images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label16_3.setText("")
        self.label16_3.setObjectName("label16_3")
        self.balance_ok = QtWidgets.QPushButton(self.balance_widget)
        self.balance_ok.setGeometry(QtCore.QRect(190, 280, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.balance_ok.setFont(font)
        self.balance_ok.setStyleSheet("QPushButton#balance_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#balance_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#balance_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.balance_ok.setObjectName("balance_ok")
        self.available_balance_head = QtWidgets.QLabel(self.balance_widget)
        self.available_balance_head.setGeometry(QtCore.QRect(120, 100, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.available_balance_head.setFont(font)
        self.available_balance_head.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.available_balance_head.setObjectName("available_balance_head")
        self.balance_amount = QtWidgets.QLabel(self.balance_widget)
        self.balance_amount.setGeometry(QtCore.QRect(230, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        self.balance_amount.setFont(font)
        self.balance_amount.setStyleSheet("color:rgba(255,255,255,230);\n"
"")
        self.balance_amount.setObjectName("balance_amount")
        self.rupee_icon = QtWidgets.QLabel(self.balance_widget)
        self.rupee_icon.setGeometry(QtCore.QRect(200, 178, 31, 31))
        self.rupee_icon.setStyleSheet("border-image:  url(:/images/icons8-rupee-96.png) 0 0 0 0 stretch stretch;\n"
"opacity:0.3;")
        self.rupee_icon.setText("")
        self.rupee_icon.setObjectName("rupee_icon")
        self.transaction_completed_widget = QtWidgets.QWidget(self.centralwidget)
        self.transaction_completed_widget.setGeometry(QtCore.QRect(3560, 500, 521, 261))
        self.transaction_completed_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.transaction_completed_widget.setObjectName("transaction_completed_widget")
        self.label16_4 = QtWidgets.QLabel(self.transaction_completed_widget)
        self.label16_4.setGeometry(QtCore.QRect(30, 10, 461, 241))
        self.label16_4.setStyleSheet("background-image:url(:/images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label16_4.setText("")
        self.label16_4.setObjectName("label16_4")
        self.transaction_completed_ok = QtWidgets.QPushButton(self.transaction_completed_widget)
        self.transaction_completed_ok.setGeometry(QtCore.QRect(190, 190, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.transaction_completed_ok.setFont(font)
        self.transaction_completed_ok.setStyleSheet("QPushButton#transaction_completed_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#transaction_completed_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#transaction_completed_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.transaction_completed_ok.setObjectName("transaction_completed_ok")
        self.transation_completed_head = QtWidgets.QLabel(self.transaction_completed_widget)
        self.transation_completed_head.setGeometry(QtCore.QRect(70, 50, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.transation_completed_head.setFont(font)
        self.transation_completed_head.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.transation_completed_head.setObjectName("transation_completed_head")
        self.completed_icon = QtWidgets.QLabel(self.transaction_completed_widget)
        self.completed_icon.setGeometry(QtCore.QRect(230, 110, 61, 61))
        self.completed_icon.setStyleSheet("border-image:url(:/images/checklist.png) 0 0 0 0 stretch stretch;")
        self.completed_icon.setText("")
        self.completed_icon.setObjectName("completed_icon")
        self.transaction_completed_widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.transaction_completed_widget_2.setGeometry(QtCore.QRect(3250, 820, 521, 261))
        self.transaction_completed_widget_2.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.transaction_completed_widget_2.setObjectName("transaction_completed_widget_2")
        self.label16_5 = QtWidgets.QLabel(self.transaction_completed_widget_2)
        self.label16_5.setGeometry(QtCore.QRect(30, 10, 461, 241))
        self.label16_5.setStyleSheet("background-image:url(:/images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.label16_5.setText("")
        self.label16_5.setObjectName("label16_5")
        self.transaction_completed_ok_2 = QtWidgets.QPushButton(self.transaction_completed_widget_2)
        self.transaction_completed_ok_2.setGeometry(QtCore.QRect(190, 190, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.transaction_completed_ok_2.setFont(font)
        self.transaction_completed_ok_2.setStyleSheet("QPushButton#transaction_completed_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#transaction_completed_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#transaction_completed_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.transaction_completed_ok_2.setObjectName("transaction_completed_ok_2")
        self.transation_completed_head_2 = QtWidgets.QLabel(self.transaction_completed_widget_2)
        self.transation_completed_head_2.setGeometry(QtCore.QRect(70, 50, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.transation_completed_head_2.setFont(font)
        self.transation_completed_head_2.setStyleSheet("color:rgba(255,255,255,200);\n"
"")
        self.transation_completed_head_2.setObjectName("transation_completed_head_2")
        self.completed_icon_2 = QtWidgets.QLabel(self.transaction_completed_widget_2)
        self.completed_icon_2.setGeometry(QtCore.QRect(230, 110, 61, 61))
        self.completed_icon_2.setStyleSheet("border-image:url(:/images/checklist.png) 0 0 0 0 stretch stretch;")
        self.completed_icon_2.setText("")
        self.completed_icon_2.setObjectName("completed_icon_2")
        self.transaction_aborted_widget = QtWidgets.QWidget(self.centralwidget)
        self.transaction_aborted_widget.setGeometry(QtCore.QRect(2400, 510, 521, 261))
        self.transaction_aborted_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.transaction_aborted_widget.setObjectName("transaction_aborted_widget")
        self.transaction_aborted_background = QtWidgets.QLabel(self.transaction_aborted_widget)
        self.transaction_aborted_background.setGeometry(QtCore.QRect(30, 10, 461, 241))
        self.transaction_aborted_background.setStyleSheet("background-image:url(:/images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.transaction_aborted_background.setText("")
        self.transaction_aborted_background.setObjectName("transaction_aborted_background")
        self.transaction_aborted_ok = QtWidgets.QPushButton(self.transaction_aborted_widget)
        self.transaction_aborted_ok.setGeometry(QtCore.QRect(190, 190, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.transaction_aborted_ok.setFont(font)
        self.transaction_aborted_ok.setStyleSheet("QPushButton#transaction_aborted_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#transaction_aborted_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#transaction_aborted_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.transaction_aborted_ok.setObjectName("transaction_aborted_ok")
        self.transation_aborted_head = QtWidgets.QLabel(self.transaction_aborted_widget)
        self.transation_aborted_head.setGeometry(QtCore.QRect(90, 50, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.transation_aborted_head.setFont(font)
        self.transation_aborted_head.setStyleSheet("color:rgba(255,100,25,200);\n"
"")
        self.transation_aborted_head.setObjectName("transation_aborted_head")
        self.transaction_aborted_Xicon = QtWidgets.QLabel(self.transaction_aborted_widget)
        self.transaction_aborted_Xicon.setGeometry(QtCore.QRect(230, 100, 71, 71))
        self.transaction_aborted_Xicon.setStyleSheet("border-image:url(:/images/cancel.png) 0 0 0 0 stretch stretch;")
        self.transaction_aborted_Xicon.setText("")
        self.transaction_aborted_Xicon.setObjectName("transaction_aborted_Xicon")
        self.Authentication_failed_widget = QtWidgets.QWidget(self.centralwidget)
        self.Authentication_failed_widget.setGeometry(QtCore.QRect(1850, 650, 521, 261))
        self.Authentication_failed_widget.setStyleSheet("QPushButton #pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 68, 235), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0.778455, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(255, 255, 255, 255))\n"
"color:red;\n"
"}")
        self.Authentication_failed_widget.setObjectName("Authentication_failed_widget")
        self.authentication_failed_background = QtWidgets.QLabel(self.Authentication_failed_widget)
        self.authentication_failed_background.setGeometry(QtCore.QRect(30, 10, 461, 241))
        self.authentication_failed_background.setStyleSheet("background-image:url(:/images/rupee1.jpg);\n"
"background-repeat: no-repeat;\n"
"background-size: (831,441);\n"
"border-radius: 20px;\n"
"")
        self.authentication_failed_background.setText("")
        self.authentication_failed_background.setObjectName("authentication_failed_background")
        self.authentication_failed_ok = QtWidgets.QPushButton(self.Authentication_failed_widget)
        self.authentication_failed_ok.setGeometry(QtCore.QRect(190, 190, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.authentication_failed_ok.setFont(font)
        self.authentication_failed_ok.setStyleSheet("QPushButton#authentication_failed_ok {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.897, x2:1, y2:0.631, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#authentication_failed_ok:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.134328, y1:0.846, x2:0.925, y2:0.142, stop:0 rgba(0, 0, 68, 255), stop:1 rgba(10, 63, 131, 255));\n"
"}\n"
"\n"
"QPushButton#authentication_failed_ok:pressed {\n"
"   padding-left:5px;\n"
"   padding-right:5px;\n"
"   padding-top:5px;\n"
"}")
        self.authentication_failed_ok.setObjectName("authentication_failed_ok")
        self.Authentication_failed_head = QtWidgets.QLabel(self.Authentication_failed_widget)
        self.Authentication_failed_head.setGeometry(QtCore.QRect(90, 50, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Authentication_failed_head.setFont(font)
        self.Authentication_failed_head.setStyleSheet("color:rgba(255,100,25,200);\n"
"")
        self.Authentication_failed_head.setObjectName("Authentication_failed_head")
        self.authentication_failed_warning_icon = QtWidgets.QLabel(self.Authentication_failed_widget)
        self.authentication_failed_warning_icon.setGeometry(QtCore.QRect(230, 100, 71, 71))
        self.authentication_failed_warning_icon.setStyleSheet("border-image:url(:/images/icons8-warning-96.png) 0 0 0 0 stretch stretch;")
        self.authentication_failed_warning_icon.setText("")
        self.authentication_failed_warning_icon.setObjectName("authentication_failed_warning_icon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 4095, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Log In"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Account Number"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Login.setText(_translate("MainWindow", "Log In"))
        self.label_3.setText(_translate("MainWindow", "Don\'t have acount?"))
        self.Create_account.setText(_translate("MainWindow", "Create Account"))
        self.label_5.setText(_translate("MainWindow", "Create Account"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Name"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Create Password"))
        self.Create_account_2.setText(_translate("MainWindow", "Create Account"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Deposit Amount"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Phone Number"))
        self.deposit.setText(_translate("MainWindow", "Deposit"))
        self.withdrawl.setText(_translate("MainWindow", "Withdrawl"))
        self.transfer.setText(_translate("MainWindow", "Transfer"))
        self.check_balance.setText(_translate("MainWindow", "Check Balance"))
        self.log_out.setText(_translate("MainWindow", "Log Out"))
        self.user_name.setText(_translate("MainWindow", "User Name"))
        self.label_7.setText(_translate("MainWindow", "Account Number:"))
        self.label_8.setText(_translate("MainWindow", "XXX XXX XXX"))
        self.deposit_head.setText(_translate("MainWindow", "Dioposit"))
        self.deposit_amount.setPlaceholderText(_translate("MainWindow", "Enter Amount"))
        self.deposit_ok.setText(_translate("MainWindow", "Ok"))
        self.withdrawl_head.setText(_translate("MainWindow", "Withdraw"))
        self.withdrawl_amount.setPlaceholderText(_translate("MainWindow", "Enter Amount"))
        self.withdrawl_ok.setText(_translate("MainWindow", "Ok"))
        self.transfer_head.setText(_translate("MainWindow", "Transfer"))
        self.transfer_account.setPlaceholderText(_translate("MainWindow", "Receiver Account NUmber"))
        self.transfer_ok.setText(_translate("MainWindow", "Ok"))
        self.transfer_amount.setPlaceholderText(_translate("MainWindow", "Enter Amount"))
        self.balance_ok.setText(_translate("MainWindow", "Ok"))
        self.available_balance_head.setText(_translate("MainWindow", "Available Balance"))
        self.balance_amount.setText(_translate("MainWindow", "XXXX"))
        self.transaction_completed_ok.setText(_translate("MainWindow", "Ok"))
        self.transation_completed_head.setText(_translate("MainWindow", "Transaction Succesful"))
        self.transaction_completed_ok_2.setText(_translate("MainWindow", "Ok"))
        self.transation_completed_head_2.setText(_translate("MainWindow", "Transaction Succesful"))
        self.transaction_aborted_ok.setText(_translate("MainWindow", "Ok"))
        self.transation_aborted_head.setText(_translate("MainWindow", "Transaction Aborted"))
        self.authentication_failed_ok.setText(_translate("MainWindow", "Ok"))
        self.Authentication_failed_head.setText(_translate("MainWindow", "Authentication failed"))
import resources_rc
