# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Text_to_speech.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 630)
        MainWindow.setWindowIcon(QtGui.QIcon("wave-sound.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color:#ffffff")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(70, 60, 781, 501))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setPlaceholderText("Write something here..!")
        self.textEdit.setStyleSheet("font: 20px;border-radius:10px;background-color:#edf0f5;"
                                    "padding-left:20; padding-top:20;")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 10, 220, 41))
        self.label.setStyleSheet("color:#5a96fa")
        
        self.speak = QtWidgets.QPushButton(self.centralwidget)
        self.speak.setGeometry(QtCore.QRect(450, 550, 50, 50))
        self.speak.setStyleSheet("""font: 10 20pt;\n""")
        self.speak.setIcon(QtGui.QIcon("wave-sound.png"))
        self.speak.setStyleSheet("""QPushButton{background-color:skyblue;border:none;border-radius:5px;}
                                   QPushButton:hover{background-color:#5a96fa;}""")
        font = QtGui.QFont()
        font.setFamily("qtquickcontrols")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text To Speech Converter"))
        self.label.setText(_translate("MainWindow", "Text To Speech"))
